version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: evol93/todo_list:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/ 
      - media_value:/var/html/media/
    depends_on: 
      - backend

volumes:
  postgres_data:
  static_value:
  media_value: